#!/usr/bin/env bash
# scripts/lib/parse-profiles.sh — Parse services/profiles.yaml into Make variable assignments.
#
# Usage (from repo root):
#   scripts/lib/parse-profiles.sh > .make/profiles.mk
#
# Stdout: Make variable assignments (pure, suitable for direct redirection).
# Stderr: Log messages via common.sh helpers.
#
# Requires: awk (POSIX), bash 3.2+
# No external deps (no yq, jq, python).

set -euo pipefail

SCRIPT_DIR="$(CDPATH="" cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

PROFILES_YAML="${PROFILES_YAML:-services/profiles.yaml}"

# ---------------------------------------------------------------------------
# Validate input
# ---------------------------------------------------------------------------

if [[ ! -f "$PROFILES_YAML" ]]; then
  die "profiles.yaml not found at '$PROFILES_YAML'. Run from repo root."
fi

log_info "Parsing $PROFILES_YAML"

# ---------------------------------------------------------------------------
# Parse with awk — POSIX-compatible, no external deps
#
# YAML shape we handle:
#   <profile-name>:            ← top-level key (no leading spaces)
#     description: '...'
#     services:
#       - service-a            ← 4-space indent + "- " prefix
#       - service-b
#   or:
#     services: '*'            ← wildcard
#
# Rules:
#   1. Lines starting with '#' are skipped.
#   2. A line matching /^[a-z]/ (no leading space, ends with ':') is a new
#      profile name — flush the previous profile, start collecting the new one.
#   3. A line matching /^\s+services:\s+'?\*'?/ is a wildcard services line.
#   4. A line matching /^\s+-\s+\S+/ is a list item — collect as a service.
#   5. At EOF, flush the final profile.
#
# Output format:
#   # Generated by scripts/lib/parse-profiles.sh — do not edit manually
#   # Source: services/profiles.yaml
#
#   ALL_PROFILES := think reason ultra-instinct
#
#   PROFILE_THINK_SERVICES := flash sonic strange friday-collector cortex
#   PROFILE_REASON_SERVICES := cortex flash strange sonic otel
#   PROFILE_ULTRA_INSTINCT_SERVICES := *
# ---------------------------------------------------------------------------

awk '
# Helper: store a completed profile — defined first (POSIX awk collects functions
# before executing rules, but declaring first avoids ambiguity in older awk variants).
function store_profile(name, services, wildcard) {
    profile_count++
    profiles[profile_count] = name
    svc_map[name] = wildcard ? "*" : services
}

# Skip blank lines and comment lines
/^[[:space:]]*#/ { next }
/^[[:space:]]*$/ { next }

# Top-level key (profile name): no leading whitespace, ends with ":"
/^[a-z][a-zA-Z0-9_-]*:/ {
    if (current_profile != "") {
        store_profile(current_profile, current_services, is_wildcard)
    }
    current_profile = $1
    sub(/:$/, "", current_profile)
    current_services = ""
    is_wildcard = 0
    next
}

# Wildcard services line:  services: "*"  or  services: '"'"'*'"'"'
/^[[:space:]]+services:[[:space:]]*('"'"'?\*'"'"'|"\*")/ {
    is_wildcard = 1
    next
}

# List item under services:  "    - service-name"
# $2 is always the name; $NF would be wrong when inline comments are present.
/^[[:space:]]+-[[:space:]]+[a-zA-Z0-9_-]+/ {
    svc = $2
    sub(/#.*$/, "", svc)
    gsub(/[[:space:]]/, "", svc)
    if (svc == "") next
    current_services = (current_services == "") ? svc : current_services " " svc
    next
}

END {
    # Flush the last profile
    if (current_profile != "") {
        store_profile(current_profile, current_services, is_wildcard)
    }

    # Build ALL_PROFILES list
    all_profiles = ""
    for (i = 1; i <= profile_count; i++) {
        if (all_profiles == "") {
            all_profiles = profiles[i]
        } else {
            all_profiles = all_profiles " " profiles[i]
        }
    }

    # Emit header
    print "# Generated by scripts/lib/parse-profiles.sh \342\200\224 do not edit manually"
    print "# Source: services/profiles.yaml"
    print ""
    print "ALL_PROFILES := " all_profiles

    # Emit per-profile variable
    for (i = 1; i <= profile_count; i++) {
        name = profiles[i]

        # Transform name to Make variable: replace - with _, uppercase
        var_name = toupper(name)
        gsub(/-/, "_", var_name)

        print ""
        print "PROFILE_" var_name "_SERVICES := " svc_map[name]
    }
}
' "$PROFILES_YAML"

log_success "profiles.mk generated from $PROFILES_YAML"
