// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/bootstrap": {
            "post": {
                "description": "Starts a bootstrap run in the background. All 4 phases (Postgres, NATS, Pulsar, Redis) run concurrently. Returns 202 immediately; poll /ready or /health/deep to track completion.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bootstrap"
                ],
                "summary": "Trigger platform bootstrap",
                "responses": {
                    "202": {
                        "description": "Bootstrap accepted — run started",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "Bootstrap already in progress",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Always returns 200. Indicates the process is alive. Use /health/deep for dependency health.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "mode": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/health/deep": {
            "get": {
                "description": "Probes Postgres, NATS, Pulsar, and Redis concurrently. Returns 503 if any probe fails.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Deep dependency health",
                "responses": {
                    "200": {
                        "description": "All dependencies healthy",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "dependencies": {
                                    "type": "object"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "One or more dependencies unhealthy",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "dependencies": {
                                    "type": "object"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns 200 only after a successful bootstrap run completes. Use as a Kubernetes readiness probe.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Bootstrap readiness",
                "responses": {
                    "200": {
                        "description": "Bootstrap complete — service ready",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "ready": {
                                    "type": "boolean"
                                }
                            }
                        }
                    },
                    "503": {
                        "description": "Bootstrap not yet complete",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "ready": {
                                    "type": "boolean"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "A.R.C. Cortex API",
	Description:      "Cortex bootstrap service — provisions Postgres, NATS, Pulsar, and Redis, then exposes a health/status HTTP API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
